arm_position_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm1_base_bridge_joint
    - arm1_bridge_housing_joint
    - arm1_housing_wrist_link_joint
    - arm1_wrist_link_wrist_cuff_joint
    - arm1_base_fixed_base_joint
  gains:
    arm1_base_bridge_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_bridge_housing_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_housing_wrist_link_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_wrist_link_wrist_cuff_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_base_fixed_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_position_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm1_palm_finger_thumb_joint
    - arm1_palm_hub_left_joint
    - arm1_hub_left_finger_left_joint
    - arm1_palm_hub_right_joint
    - arm1_hub_right_finger_right_joint
  gains:
    arm1_palm_finger_thumb_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_palm_hub_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_hub_left_finger_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_palm_hub_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_hub_right_finger_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1